server:
  port : 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TMTM?useSSL=false
    #    url: jdbc:mysql://ls-52bfd449394926c12c17858435de4a71085d20ac.cpqaprbpusy4.ap-northeast-2.rds.amazonaws.com:3306/TMTMDB
    username: root
    password: Dhsk5656!
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google-AoS:
            client-id: 317253442779-aj2npvsq0m9r6op406ej550cheqm5qdj.apps.googleusercontent.com
            scope:
              - email
              - profile
            provider: google
          google-ioS:
            client-id: 317253442779-7iq9rqdlmkut3i60giveb7bf28kosacr.apps.googleusercontent.com
            scope:
              - email
              - profile
            provider: google
          google-WEB:
            client-id: 317253442779-2n3971n1mg5p0piue9ekfl9bnt20v41p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            provider: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub